<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VWSWX017-US" name="com.tudor.swag.tests.suites.CubeSuite" tests="9" failures="0" timestamp="4 Jun 2021 16:05:02 GMT" time="380.960" errors="6">
  <testcase name="verifyData" time="9.364" classname="com.tudor.swag.tests.suites.CubeSuite">
    <error type="java.lang.AssertionError" message="The following asserts failed:

[Row: 2] [Column: 3] [Expected: -10,775,363,594.721382] [Actual: -10,775,363,594.721384], 
[Row: 4] [Column: 3] [Expected: -10,335,961,660.392012] [Actual: -10,335,961,660.39201]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

[Row: 2] [Column: 3] [Expected: -10,775,363,594.721382] [Actual: -10,775,363,594.721384], 
[Row: 4] [Column: 3] [Expected: -10,335,961,660.392012] [Actual: -10,335,961,660.39201]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertAll(SoftAssertSwag.java:573)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:432)
	at com.tudor.swag.tests.suites.CubeSuite.verifyData(CubeSuite.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="8.712" classname="com.tudor.swag.tests.suites.CubeSuite">
    <error type="java.lang.AssertionError" message="The following asserts failed:

[Row: 2] [Column: 3] [Expected: -19,005,187,292.392773] [Actual: -19,005,187,292.39278], 
[Row: 6] [Column: 3] [Expected: -11,884,679,972.561125] [Actual: -11,884,679,972.561123]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

[Row: 2] [Column: 3] [Expected: -19,005,187,292.392773] [Actual: -19,005,187,292.39278], 
[Row: 6] [Column: 3] [Expected: -11,884,679,972.561125] [Actual: -11,884,679,972.561123]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertAll(SoftAssertSwag.java:573)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:432)
	at com.tudor.swag.tests.suites.CubeSuite.verifyData(CubeSuite.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="95.515" classname="com.tudor.swag.tests.suites.CubeSuite">
    <error type="java.lang.AssertionError" message="Prod return Exception, Alpha return data expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Prod return Exception, Alpha return data expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:423)
	at com.tudor.swag.tests.suites.CubeSuite.verifyData(CubeSuite.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="96.676" classname="com.tudor.swag.tests.suites.CubeSuite">
    <error type="java.lang.AssertionError" message="Prod return Exception, Alpha return data expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Prod return Exception, Alpha return data expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:423)
	at com.tudor.swag.tests.suites.CubeSuite.verifyData(CubeSuite.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="19.763" classname="com.tudor.swag.tests.suites.CubeSuite"/>
  <testcase name="verifyData" time="11.012" classname="com.tudor.swag.tests.suites.CubeSuite">
    <error type="java.lang.AssertionError" message="The following asserts failed:

[Row: 3] [Column: 3] [Expected: -10,450,435,953.219822] [Actual: -10,450,435,953.219824], 
[Row: 6] [Column: 3] [Expected: -9,918,452,801.226772] [Actual: -9,918,452,801.22677]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

[Row: 3] [Column: 3] [Expected: -10,450,435,953.219822] [Actual: -10,450,435,953.219824], 
[Row: 6] [Column: 3] [Expected: -9,918,452,801.226772] [Actual: -9,918,452,801.22677]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertAll(SoftAssertSwag.java:573)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:432)
	at com.tudor.swag.tests.suites.CubeSuite.verifyData(CubeSuite.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="100.735" classname="com.tudor.swag.tests.suites.CubeSuite">
    <error type="java.lang.AssertionError" message="Prod return Exception, Alpha return data expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Prod return Exception, Alpha return data expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:423)
	at com.tudor.swag.tests.suites.CubeSuite.verifyData(CubeSuite.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="19.034" classname="com.tudor.swag.tests.suites.CubeSuite"/>
  <testcase name="verifyData" time="20.149" classname="com.tudor.swag.tests.suites.CubeSuite"/>
</testsuite> <!-- com.tudor.swag.tests.suites.CubeSuite -->
