<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VWSWX017-US" name="com.tudor.swag.tests.suites.PnLSuite" tests="8" failures="0" timestamp="18 May 2021 14:55:43 GMT" time="1098.562" errors="3">
  <testcase name="verifyData" time="22.014" classname="com.tudor.swag.tests.suites.PnLSuite"/>
  <testcase name="verifyData" time="11.764" classname="com.tudor.swag.tests.suites.PnLSuite"/>
  <testcase name="verifyData" time="27.116" classname="com.tudor.swag.tests.suites.PnLSuite"/>
  <testcase name="verifyData" time="13.629" classname="com.tudor.swag.tests.suites.PnLSuite"/>
  <testcase name="verifyData" time="10.506" classname="com.tudor.swag.tests.suites.PnLSuite">
    <error type="java.lang.AssertionError" message="Actual row count is not equal as expected expected [80] but found [78]">
      <![CDATA[java.lang.AssertionError: Actual row count is not equal as expected expected [80] but found [78]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertTableData(SoftAssertSwag.java:223)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:431)
	at com.tudor.swag.tests.suites.PnLSuite.verifyData(PnLSuite.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="7.508" classname="com.tudor.swag.tests.suites.PnLSuite">
    <error type="java.lang.AssertionError" message="Actual row count is not equal as expected expected [54] but found [52]">
      <![CDATA[java.lang.AssertionError: Actual row count is not equal as expected expected [54] but found [52]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertTableData(SoftAssertSwag.java:223)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:431)
	at com.tudor.swag.tests.suites.PnLSuite.verifyData(PnLSuite.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="968.953" classname="com.tudor.swag.tests.suites.PnLSuite">
    <error type="java.lang.AssertionError" message="The following asserts failed:

[Row: 130] [Column: 4] [Expected: -67,326.06472337905] [Actual: -67,326.06472337904], 
[Row: 221] [Column: 4] [Expected: -30,051.113208964154] [Actual: -30,051.11320896415], 
[Row: 44601] [Column: 4] [Expected: 217,927.06098074274] [Actual: 217,927.0609807427], 
[Row: 44832] [Column: 4] [Expected: 62,703.50065749427] [Actual: 62,703.500657494274], 
[Row: 44883] [Column: 4] [Expected: -109,523.62085968624] [Actual: -109,523.62085968626], 
[Row: 44890] [Column: 4] [Expected: 51,128.853548831896] [Actual: 51,128.85354883191], 
[Row: 45052] [Column: 4] [Expected: 174,509.13221011168] [Actual: 174,509.13221011165], 
[Row: 45079] [Column: 4] [Expected: -247,076.27943817576] [Actual: -247,076.27943817578], 
[Row: 45744] [Column: 4] [Expected: -386.6062571432182] [Actual: -386.60625714321816], 
[Row: 45833] [Column: 4] [Expected: 1,172.5529863013699] [Actual: 1,172.55298630137], 
[Row: 46022] [Column: 4] [Expected: -4.842603926910603] [Actual: -4.842603926910602]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

[Row: 130] [Column: 4] [Expected: -67,326.06472337905] [Actual: -67,326.06472337904], 
[Row: 221] [Column: 4] [Expected: -30,051.113208964154] [Actual: -30,051.11320896415], 
[Row: 44601] [Column: 4] [Expected: 217,927.06098074274] [Actual: 217,927.0609807427], 
[Row: 44832] [Column: 4] [Expected: 62,703.50065749427] [Actual: 62,703.500657494274], 
[Row: 44883] [Column: 4] [Expected: -109,523.62085968624] [Actual: -109,523.62085968626], 
[Row: 44890] [Column: 4] [Expected: 51,128.853548831896] [Actual: 51,128.85354883191], 
[Row: 45052] [Column: 4] [Expected: 174,509.13221011168] [Actual: 174,509.13221011165], 
[Row: 45079] [Column: 4] [Expected: -247,076.27943817576] [Actual: -247,076.27943817578], 
[Row: 45744] [Column: 4] [Expected: -386.6062571432182] [Actual: -386.60625714321816], 
[Row: 45833] [Column: 4] [Expected: 1,172.5529863013699] [Actual: 1,172.55298630137], 
[Row: 46022] [Column: 4] [Expected: -4.842603926910603] [Actual: -4.842603926910602]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertAll(SoftAssertSwag.java:490)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:432)
	at com.tudor.swag.tests.suites.PnLSuite.verifyData(PnLSuite.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="37.072" classname="com.tudor.swag.tests.suites.PnLSuite"/>
</testsuite> <!-- com.tudor.swag.tests.suites.PnLSuite -->
