<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VWSWX017-US" name="com.tudor.swag.tests.suites.OrdersSuite" tests="15" failures="0" timestamp="20 May 2021 13:30:55 GMT" time="409.585" errors="3">
  <testcase name="verifyData" time="8.235" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="99.393" classname="com.tudor.swag.tests.suites.OrdersSuite">
    <error type="java.lang.AssertionError" message="Prod return data, Alpha return Exception expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Prod return data, Alpha return Exception expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:428)
	at com.tudor.swag.tests.suites.OrdersSuite.verifyData(OrdersSuite.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="106.186" classname="com.tudor.swag.tests.suites.OrdersSuite">
    <error type="java.lang.AssertionError" message="Prod return data, Alpha return Exception expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Prod return data, Alpha return Exception expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:428)
	at com.tudor.swag.tests.suites.OrdersSuite.verifyData(OrdersSuite.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="56.126" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="6.375" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="8.633" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="45.971" classname="com.tudor.swag.tests.suites.OrdersSuite">
    <error type="java.lang.AssertionError" message="Actual row count is not equal as expected expected [138] but found [139]">
      <![CDATA[java.lang.AssertionError: Actual row count is not equal as expected expected [138] but found [139]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.tudor.swag.tests.utils.SoftAssertSwag.assertTableData(SoftAssertSwag.java:225)
	at com.tudor.swag.tests.suites.common.SwagletSuite.verifyAlphaData(SwagletSuite.java:431)
	at com.tudor.swag.tests.suites.OrdersSuite.verifyData(OrdersSuite.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyData -->
  <testcase name="verifyData" time="8.196" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="6.511" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="24.375" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="10.138" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="8.189" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="8.325" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="6.592" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
  <testcase name="verifyData" time="6.340" classname="com.tudor.swag.tests.suites.OrdersSuite"/>
</testsuite> <!-- com.tudor.swag.tests.suites.OrdersSuite -->
